language: c
compiler:
  - clang
  - gcc

os:
  - linux
dist: xenial
sudo: false

before_install:
  - sudo apt-get -y install flex bison readline

script: 
  - make

notifications:
  email: false
branches:
  only:
    - master

