language: c
compiler:
  - clang
  - gcc

os:
  - linux
dist: bionic

before_install:
  - sudo apt-get -y install flex bison pkg-config libreadline7 

script: 
  - make

notifications:
  email: false
branches:
  only:
    - master

