language: c
compiler:
  - clang
  - gcc

os:
  - linux
dist: xenial

before_install:
  - sudo apt-get -y install flex bison pkg-config lib64readline7 libreadline-dev

script: 
  - make

notifications:
  email: false
branches:
  only:
    - master

